import { describe,expect,it } from "vitest";
import { SCENARIOS, randomScenario, validateScenario } from "../simulation/scenarios";
import { simulate } from "../simulation/propagation-engine";
import { causalTrace, criticalCollapse, minimizeScenario } from "../simulation/causal-minimizer";
import { optimizeIntervention } from "../simulation/intervention-optimizer";
import { evolutionarySearch } from "../simulation/evolutionary-search";
import { analyzeRobustness,runBaselineBenchmark } from "../simulation/experiments";
import { paretoInterventions } from "../simulation/intervention-optimizer";
import { ablateCausalLinks } from "../simulation/causal-ablation";
import { importGridTopology } from "../simulation/topology-importer";
import ieee14 from "../../data/ieee14-topology.json";
import powerCase from "../../data/ieee14-powerflow.json";
import { dcPowerFlow,findWorstNMinusOne } from "../simulation/dc-power-flow";
import { runMultiSeedBenchmark } from "../simulation/statistics";
import { sensitivityAttribution } from "../simulation/experiments";
import { uncertaintyPareto } from "../simulation/robust-pareto";
import { constraintAudit } from "../simulation/candidate-constraints";

describe("simulation engine",()=>{
 it("is deterministic for a supplied seed",()=>expect(simulate(randomScenario(73))).toEqual(simulate(randomScenario(73))));
 it("honors dependency propagation delay",()=>{const r=simulate(SCENARIOS[0]);const payment=r.events.find(e=>e.nodeId==="payments"&&e.kind==="dependency");expect(payment?.tick).toBeGreaterThanOrEqual(2)});
 it("activates backup capacity",()=>expect(simulate(SCENARIOS[0]).events.some(e=>e.kind==="backup"&&e.nodeId==="telecom-auth")).toBe(true));
 it("recovers after a finite shock",()=>{const r=simulate(SCENARIOS[2]);expect(r.timeline.at(-1)!.nodes.find(n=>n.id==="bridge")!.capacity).toBeGreaterThan(r.timeline[2].nodes.find(n=>n.id==="bridge")!.capacity)});
 it("calculates cascade metrics",()=>{const m=simulate(SCENARIOS[0]).finalMetrics;expect(m.cascadeDepth).toBeGreaterThan(2);expect(m.severity).toBeGreaterThan(0)});
 it("rejects invalid scenarios",()=>expect(()=>validateScenario({id:"x",name:"x",description:"x",seed:1,duration:-1,shocks:[]})).toThrow());
 it("builds a trace from actual causal events",()=>{const r=simulate(SCENARIOS[0]);const trace=causalTrace(r);expect(trace.length).toBeGreaterThan(2);expect(trace.every(e=>r.events.includes(e))).toBe(true)});
 it("minimizes while preserving collapse",()=>{const composite={...SCENARIOS[0],shocks:[...SCENARIOS[0].shocks,{id:"irrelevant",nodeId:"school",start:0,duration:1,intensity:10,label:"Minor"}]};const m=minimizeScenario(composite);expect(m.scenario.shocks.length).toBeLessThan(composite.shocks.length);expect(criticalCollapse(m.result)).toBe(true)});
 it("minimization never mutates the source scenario",()=>{const source=structuredClone(SCENARIOS[0]),before=structuredClone(source);minimizeScenario(source);expect(source).toEqual(before)});
 it("finds the offline-payment intervention and prevents target collapse",()=>{const o=optimizeIntervention(SCENARIOS[0]);expect(o.intervention?.id).toBe("offline-fuel");expect(criticalCollapse(o.after)).toBe(false)});
 it("search improves over initialization",()=>{const p=evolutionarySearch(8,7,20);expect(Math.max(...p.slice(1).map(x=>x.bestFitness))).toBeGreaterThanOrEqual(p[0].bestFitness)});
 it("increasing redundancy never worsens availability",()=>{const base=simulate(SCENARIOS[0]);const hardened=simulate(SCENARIOS[0],{id:"p",label:"p",description:"p",type:"backup",nodeId:"telecom-auth",value:40,cost:1});base.timeline.forEach((t,i)=>expect(hardened.timeline[i].metrics.criticalServicesAvailable).toBeGreaterThanOrEqual(t.metrics.criticalServicesAvailable))});
 it("compares search methods under equal deterministic budgets",()=>{const a=runBaselineBenchmark(11,24),b=runBaselineBenchmark(11,24);expect(a).toEqual(b);expect(new Set(a.map(x=>x.simulations))).toEqual(new Set([24]));expect(a).toHaveLength(4)});
 it("quantifies robustness reproducibly",()=>{const a=analyzeRobustness(SCENARIOS[0],19,20);expect(a).toEqual(analyzeRobustness(SCENARIOS[0],19,20));expect(a.collapseProbability).toBeGreaterThanOrEqual(0);expect(a.collapseProbability).toBeLessThanOrEqual(1);expect(a.severityP90).toBeGreaterThanOrEqual(a.severityP10)});
 it("returns only non-dominated intervention solutions",()=>{const frontier=paretoInterventions(SCENARIOS[0]);expect(frontier.length).toBeGreaterThan(0);frontier.forEach(a=>expect(frontier.some(b=>b!==a&&b.cost<=a.cost&&b.severity<=a.severity&&(b.cost<a.cost||b.severity<a.severity))).toBe(false))});
 it("falsifies causal links by replaying edge deletion",()=>{const ablations=ablateCausalLinks(SCENARIOS[0]);expect(ablations.length).toBeGreaterThan(1);expect(ablations.some(a=>a.necessary&&a.preventedCollapse)).toBe(true)});
 it("imports and validates the public IEEE 14-bus topology",()=>{const model=importGridTopology(ieee14);expect(model.nodes).toHaveLength(14);expect(model.dependencies).toHaveLength(40);expect(model.metadata.source).toBe("MATPOWER case14")});
 it("solves IEEE-14 DC power flow and an N-1 overload cascade",()=>{const base=dcPowerFlow(powerCase);expect(base.flows).toHaveLength(20);expect(Object.keys(base.angles)).toHaveLength(14);const worst=findWorstNMinusOne(powerCase);expect(worst.outages.length).toBeGreaterThanOrEqual(1);expect(worst.iterations).toBeGreaterThanOrEqual(1)});
 it("aggregates benchmark evidence across seeds with a confidence interval",()=>{const r=runMultiSeedBenchmark(4,20);expect(r.seeds).toBe(4);expect(r.ci95[1]).toBeGreaterThanOrEqual(r.ci95[0]);expect(r.meanImprovement).toBeGreaterThan(0)});
 it("attributes uncertainty sensitivity",()=>{const a=sensitivityAttribution(analyzeRobustness(SCENARIOS[0],5,24));expect(a).toHaveLength(3);expect(a.reduce((s,x)=>s+x.share,0)).toBeCloseTo(1);expect(a[0].share).toBeGreaterThanOrEqual(a[2].share)});
 it("builds an uncertainty-aware intervention frontier",()=>{const p=uncertaintyPareto(SCENARIOS[0],7,8,2);expect(p.length).toBeGreaterThan(0);expect(p.every(x=>x.collapseProbability>=0&&x.collapseProbability<=1)).toBe(true)});
 it("records explicit candidate rejection reasons",()=>{const audit=constraintAudit();expect(audit.filter(x=>!x.valid)).toHaveLength(3);expect(audit.at(-1)?.valid).toBe(true)});
});
