"use client";
import { CheckCircle2,ShieldAlert,Zap } from "lucide-react";
import { runMultiSeedBenchmark } from "@/simulation/statistics";
import { sensitivityAttribution } from "@/simulation/experiments";
import { uncertaintyPareto } from "@/simulation/robust-pareto";
import { findWorstNMinusOne } from "@/simulation/dc-power-flow";
import { constraintAudit } from "@/simulation/candidate-constraints";

type Data={multi:ReturnType<typeof runMultiSeedBenchmark>;sensitivity:ReturnType<typeof sensitivityAttribution>;robustPareto:ReturnType<typeof uncertaintyPareto>;grid:ReturnType<typeof findWorstNMinusOne>;constraints:ReturnType<typeof constraintAudit>};
export function AdvancedEvidence({data}:{data:Data}){return <section className="advanced-evidence"><div className="advanced-head"><span>PUBLICATION-GRADE EXTENSIONS</span><h2>Evidence across seeds, physics, and uncertainty.</h2></div><div className="advanced-grid"><article><div className="panel-title"><span>05</span> Multi-seed confidence interval</div><div className="headline-stat"><b>{data.multi.meanImprovement.toFixed(2)}×</b><span>mean collapse-discovery ratio<br/>across {data.multi.seeds} independent seeds</span></div><p>95% CI [{data.multi.ci95[0].toFixed(2)}, {data.multi.ci95[1].toFixed(2)}] · evolutionary wins {data.multi.wins}/{data.multi.seeds} · {data.multi.budgetPerMethod} simulations/method/seed</p></article><article><div className="panel-title"><span>06</span> Sensitivity attribution</div>{data.sensitivity.map(s=><div className="sensitivity-row" key={s.parameter}><span>{s.parameter}</span><div><i style={{width:`${s.share*100}%`}}/></div><b>{Math.round(s.share*100)}%</b><small>ρ {s.correlation.toFixed(2)}</small></div>)}</article><article><div className="panel-title"><span>07</span> IEEE-14 physical cascade</div><div className="headline-stat power"><Zap/><b>{Math.round(data.grid.unservedMW)} MW</b></div><p>Worst N−1 replay starts at line {data.grid.outages[0]} and trips {data.grid.outages.length-1} overloaded lines over {data.grid.iterations} iterations.</p><em>DC load flow uses MATPOWER demand, generation, and reactance. Thermal limits are explicitly derived experimental assumptions.</em></article><article><div className="panel-title"><span>08</span> Uncertainty-aware repair frontier</div>{data.robustPareto.slice(0,4).map(p=><div className="robust-pareto-row" key={p.interventions.map(i=>i.id).join()}><b>Cost {p.cost}</b><span>{p.interventions.map(i=>i.label).join(" + ")}</span><em>{Math.round(p.collapseProbability*100)}% collapse · median severity {p.medianSeverity}</em></div>)}</article><article className="constraint-card"><div className="panel-title"><span>09</span> Search validity firewall</div>{data.constraints.map(c=><div className="constraint-row" key={c.label}>{c.valid?<CheckCircle2/>:<ShieldAlert/>}<span><b>{c.label}</b><small>{c.valid?"ACCEPTED":c.reasons.join(" · ")}</small></span></div>)}</article></div></section>}
